### ISSUE TITLE
My setup: Am I being thick?

### ISSUE THREAD

**Issue by JoeThompsonGitHub** [jneilliii/OctoPrint-Tasmota#100]
Hi, and thankyou for your continued hard work in developing some amazing plugins.

Could you help me to understand my issue?

My setup is:

Tasmota sonoff controlling printer power (tested using m80 and 81 commands - works fine)
Raspberry Pi connected to printer - Not: 5v from pi is not feeding printer as I have removed that pin

I thought by using the M80 and my IP followed by the index at the start of my gcode in my slicer app would happily turn on the printer power and crack on with the rest of the gcode...however at this point my printer power is off and my pi is not connected to the printer as the printer is still turned off. At what point does the M80 command get used to turn on the printer?

The reason I ask is the print button is greyed out on my octopi dashboard quite rightly because my printer is off. Hopefully you can tell me where im going wrong??

Now on a side note, there is a lightening bolt on the top banner which when clicked gives me an error telling me I have a config error with my tasmota device. Ive doubled checked my settings and they are fine. Like above if I run M80 and M81 commands it toggles the switch no problem. Also on a octopi restart I notice the lighening bolt give a warning, so is the intention when octopi first boots it powers on the printer? Any help would be amazing.

Thanks

**Comment by jneilliii** [comment]
You are correct, you can't really start a print in order for the M80 to work when the printer is disconnected, This is only possible if your controller is back-powered by USB. Would be great if you could enable debug logging, restart octoprint, and then try the button again and provide logs so I can see what error you are talking about.

**Comment by JoeThompsonGitHub** [comment]
Thank you for your comments. Is this the log file you needed?

**Comment by JoeThompsonGitHub** [comment]
``[2020-11-06 20:25:09,520] ERROR: Invalid ip or unknown error connecting to 10.0.0.114.
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/pi/oprint/lib/python3.7/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/home/pi/oprint/lib/python3.7/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
OSError: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/home/pi/oprint/lib/python3.7/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/home/pi/oprint/lib/python3.7/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/home/pi/oprint/lib/python3.7/site-packages/urllib3/connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x6cc4fa50>: Failed to establish a new connection: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/pi/oprint/lib/python3.7/site-packages/urllib3/connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/pi/oprint/lib/python3.7/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='10.0.0.114', port=80): Max retries exceeded with url: /cm?user=admin&password=&cmnd=Power1%20on (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x6cc4fa50>: Failed to establish a new connection: [Errno 113] No route to host'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_tasmota/__init__.py", line 312, in turn_on
    webresponse = requests.get("http://" + plug["ip"] + "/cm?user=" + plug["username"] + "&password=" + requests.utils.quote(plug["password"]) + "&cmnd=Power" + str(plug["idx"]) + "%20on")
  File "/home/pi/oprint/lib/python3.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.0.0.114', port=80): Max retries exceeded with url: /cm?user=admin&password=&cmnd=Power1%20on (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x6cc4fa50>: Failed to establish a new connection: [Errno 113] No route to host'))
[2020-11-06 20:25:46,994] ERROR: Invalid ip or unknown error connecting to 10.0.0.114.
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_tasmota/__init__.py", line 314, in turn_on
    chk = response["POWER%s" % plug["idx"]]
KeyError: 'POWER1'
[2020-11-06 20:26:10,312] ERROR: Invalid ip or unknown error connecting to 10.0.0.114.
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_tasmota/__init__.py", line 314, in turn_on
    chk = response["POWER%s" % plug["idx"]]
KeyError: 'POWER1'
[2020-11-06 20:26:56,987] ERROR: Invalid ip or unknown error connecting to 10.0.0.114.
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_tasmota/__init__.py", line 314, in turn_on
    chk = response["POWER%s" % plug["idx"]]
KeyError: 'POWER1'
[2020-11-06 20:27:21,909] ERROR: Invalid ip or unknown error connecting to 10.0.0.114.
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_tasmota/__init__.py", line 314, in turn_on
    chk = response["POWER%s" % plug["idx"]]
KeyError: 'POWER1'
[2020-11-06 20:31:29,423] ERROR: Invalid ip or unknown error connecting to 10.0.0.114.
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_tasmota/__init__.py", line 314, in turn_on
    chk = response["POWER%s" % plug["idx"]]
KeyError: 'POWER1'
[2020-11-07 14:31:17,890] ERROR: Invalid ip or unknown error connecting to 10.0.0.114.
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_tasmota/__init__.py", line 314, in turn_on
    chk = response["POWER%s" % plug["idx"]]
KeyError: 'POWER1'
[2020-11-07 14:37:30,202] ERROR: Invalid ip or unknown error connecting to 10.0.0.114.
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_tasmota/__init__.py", line 314, in turn_on
    chk = response["POWER%s" % plug["idx"]]
KeyError: 'POWER1'
[2020-11-07 14:38:35,552] ERROR: Invalid ip or unknown error connecting to 10.0.0.114.
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_tasmota/__init__.py", line 314, in turn_on
    chk = response["POWER%s" % plug["idx"]]
KeyError: 'POWER1'
[2020-11-07 14:46:08,150] ERROR: Invalid ip or unknown error connecting to 10.0.0.114.
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_tasmota/__init__.py", line 314, in turn_on
    chk = response["POWER%s" % plug["idx"]]
KeyError: 'POWER1'

**Comment by jneilliii** [comment]
Yep, that's the errors I was looking for. Based on the error it seems that the pi is unable to see the tasmota device on the network. This would be because of wifi isolation mode or some other network related routing issue or just simply an incorrect ip address. This would be an issue outside of the plugin itself, but related to your network configuration.

**Comment by JoeThompsonGitHub** [comment]
Thanks for the reply. Only when I ping from the Pi to the Tasmota device I have no problem...

`pi@octopi:~ $ ping 10.0.0.114
PING 10.0.0.114 (10.0.0.114) 56(84) bytes of data.
64 bytes from 10.0.0.114: icmp_seq=1 ttl=255 time=95.8 ms
64 bytes from 10.0.0.114: icmp_seq=2 ttl=255 time=7.49 ms
64 bytes from 10.0.0.114: icmp_seq=3 ttl=255 time=8.14 ms
64 bytes from 10.0.0.114: icmp_seq=4 ttl=255 time=5.36 ms
64 bytes from 10.0.0.114: icmp_seq=5 ttl=255 time=2.88 ms
64 bytes from 10.0.0.114: icmp_seq=6 ttl=255 time=4.34 ms
64 bytes from 10.0.0.114: icmp_seq=7 ttl=255 time=4.75 ms
64 bytes from 10.0.0.114: icmp_seq=8 ttl=255 time=6.55 ms
64 bytes from 10.0.0.114: icmp_seq=9 ttl=255 time=5.04 ms
`

**Comment by jneilliii** [comment]
and just to confirm, you are able to get to the web interface of the Tasmota device yourself?

> Tasmota sonoff controlling printer power (tested using m80 and 81 commands - works fine)

This is unexpected, are you powering the relay from the printer board itself, or connected to the sonoff from the printer control board in some way? A little more detail to your setup might help me understand what might be happening. It almost sounds like the relay is off when octoprint attempts to connect to it.

**Comment by JoeThompsonGitHub** [comment]
Yes, I can connect to the web page no problem and toggle away.

Just to confirm the M80 10.0.0.114 1 and M81 10.0.0.114 1 also works from the octopi command input and the switch toggles fine.

My setup is, pi powered with permanent mains. Tasmota sonoff also has permanent input and the output is connected to my printer.

**Comment by JoeThompsonGitHub** [comment]
Have you tested this plugin with Tasmota 9.1.0? As thats what version im using.

**Comment by jneilliii** [comment]
That I have not tested. Let me see about upgrading one of my devices here and see what's happening.

**Comment by jneilliii** [comment]
Ok, just upgraded one of my sonoff relays to 9.1 and everything is still working as expected here for me with the navbar button. Could you please share screenshots of your plugin settings? When you press the verify button does it say everything is ok?

**Comment by JoeThompsonGitHub** [comment]
![1](https://user-images.githubusercontent.com/74116836/98695047-1a51b500-236a-11eb-86f8-3b99b1d6eb00.PNG)
![2](https://user-images.githubusercontent.com/74116836/98695049-1aea4b80-236a-11eb-9a9e-5f63556d34ff.PNG)

**Comment by JoeThompsonGitHub** [comment]
Would you recommend reinstalling plugin and starting again?

**Comment by JoeThompsonGitHub** [comment]
It seems to be working now. Since clicking verify and enabling GPIO26 and reloading octopi it seems to be working. Strange how it didnt work before. Thank you for your time on this.
