### ISSUE TITLE
Connect ok, but then "unknown error"

### ISSUE THREAD

**Issue by ilgrank** [jneilliii/OctoPrint-Tasmota#130]
Hello
I just installed the Tasmota plugin. 
My tasmota plug is running the latest version (9.2.0.7) and has no password set.
Configured a new device, let the configure SetOption26, no problem there.
Made the verification check, and it passed. But then the menu icon is grayed out and there are several communication error pop.ups. I have enabled the debugging, and the following can be seen in the logs:
```
[2021-02-13 16:26:22,301] DEBUG: abortTimeout: 120
[2021-02-13 16:26:22,304] DEBUG: powerOffWhenIdle: True
[2021-02-13 16:26:22,305] DEBUG: idleTimeout: 3
[2021-02-13 16:26:22,306] DEBUG: idleIgnoreCommands: M105
[2021-02-13 16:26:22,307] DEBUG: idleTimeoutWaitTemp: 40
[2021-02-13 16:28:18,791] DEBUG: {u'ip': u'192.168.0.61', u'command': u'checkStatus', u'idx': u'1'}
[2021-02-13 16:28:18,799] DEBUG: Checking status of 192.168.0.61 index 1.
[2021-02-13 16:28:18,801] DEBUG: {'username': 'admin', 'autoConnect': False, 'event_on_connecting': False, 'ip': '192.168.0.61', 'backlog_on_delay': 0, 'off_color': '#FF0000', 'autoDisconnectDelay': 0, 'sysCmdOff': False, 'gcodeEnabled': False, 'gcodeOnDelay': 0, 'backlog_off_delay': 0, 'label': 'TSP-01', 'warnPrinting': True, 'thermal_runaway': True, 'gcodeOffDelay': 0, 'sysCmdOnDelay': 0, 'event_on_error': True, 'label_extended': '', 'sysRunCmdOff': '', 'use_backlog': False, 'autoDisconnect': False, 'automaticShutdownEnabled': True, 'event_on_upload': False, 'sysRunCmdOn': '', 'unknown_color': '#808080', 'password': '', 'icon': 'icon-bolt', 'idx': '1', 'displayWarning': True, 'sensor_identifier': '', 'autoConnectDelay': 10, 'event_on_disconnect': True, 'sysCmdOn': False, 'sysCmdOffDelay': 0, 'currentState': 'unknown', 'on_color': '#00FF00'}
[2021-02-13 16:28:18,972] DEBUG: check status code: 200
[2021-02-13 16:28:18,972] DEBUG: check status text: {"Status":{"Module":0,"DeviceName":"TSP-01","FriendlyName":["TSP-01"],"Topic":"TSP-01","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":1,"PowerRetain":1},"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/tasmota-lite.bin.gz	","RestartReason":"Software/System restart","Uptime":"0T01:45:40","StartupUTC":"2021-02-13T14:42:38","Sleep":50,"CfgHolder":4617,"BootCount":38,"BCResetTime":"2020-04-27T10:11:56","SaveCount":173,"SaveAddress":"F9000"},"StatusFWR":{"Version":"9.2.0.7(lite)","BuildDateTime":"2021-02-13T11:17:04","Boot":31,"Core":"2_7_4_9","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8285","CR":"413/699"},"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["<redacted>",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["04008229","2805C8000100060000005A00000000000000","00000080","00006000","00000000"]},"StatusMEM":{"ProgramSize":478,"Free":524,"Heap":26,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"144051","FlashFrequency":40,"FlashMode":3,"Features":["00000809","8F000783","04108001","00000006","010001C0","00000000","00004004","00000000","00000000"],"Drivers":"1,2,3,4,9,10,16,20,21,37","Sensors":"3"},"StatusNET":{"Hostname":"TSP-01","IPAddress":"192.168.0.61","Gateway":"192.168.0.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.0.102","Mac":"<redacted>","Webserver":2,"WifiConfig":2,"WifiPower":17.0},"StatusMQT":{"MqttHost":"192.168.0.102","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_48F52E","MqttUser":"tasmotas","MqttCount":71,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30},"StatusTIM":{"UTC":"2021-02-13T16:28:18","Local":"2021-02-13T17:28:18","StartDST":"2021-03-28T02:00:00","EndDST":"2021-10-31T03:00:00","Timezone":"+01:00","Sunrise":"08:01","Sunset":"18:07"},"StatusPTH":{"PowerDelta":[0,0,0],"PowerLow":0,"PowerHigh":0,"VoltageLow":0,"VoltageHigh":0,"CurrentLow":0,"CurrentHigh":0},"StatusSNS":{"Time":"2021-02-13T17:28:18","ENERGY":{"TotalStartTime":"2020-04-27T10:08:30","Total":0.020,"Yesterday":0.000,"Today":0.020,"Power":19,"ApparentPower":30,"ReactivePower":23,"Factor":0.63,"Voltage":225,"Current":0.133}},"StatusSTS":{"Time":"2021-02-13T17:28:18","Uptime":"0T01:45:40","UptimeSec":6340,"Vcc":3.429,"Heap":26,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":71,"POWER1":"ON","Wifi":{"AP":1,"SSId":"<redacted>","BSSId":"<redacted>","Channel":11,"RSSI":80,"Signal":-60,"LinkCount":1,"Downtime":"0T00:00:03"}}}
[2021-02-13 16:28:18,973] ERROR: Invalid ip or unknown error connecting to 192.168.0.61.
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_tasmota/__init__.py", line 501, in check_status
    response = webresponse.json()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 443 (char 442)
[2021-02-13 16:28:18,983] DEBUG: 192.168.0.61 index 1 is UNKNOWN
[2021-02-13 16:28:18,984] DEBUG: unknown error with 192.168.0.61.

```
the power off on idle timeout works btw, it's just that I can't control the plug from the icon, and the status icon stays grayed out.
<img width="510" alt="tasmota" src="https://user-images.githubusercontent.com/4583412/107853782-3e64dc80-6e18-11eb-9b38-d7928609afff.PNG">

is there something I can do to further troubleshoot it? 
Thanks!

**Comment by jneilliii** [comment]
can you drag your whole log file into a comment here please to share? It looks like some of the lines got cut off and end with $.

**Comment by ilgrank** [comment]
sorry, didn't notice it was cut, I re-pasted it above

**Comment by ilgrank** [comment]
Sorry to bring this up again... but have you had the chance to see the full log?
Thanks!

**Comment by jneilliii** [comment]
Sorry I have not, but just took a quick look and only see one thing that might be out of sorts with the response from your device. Can you check the firmware update URL and make sure to delete the tab at the end of the input? It seems to possibly have been inserted and not sure if that's causing an issue with the json parsing (even though it shouldn't).

**Comment by ilgrank** [comment]
..and indeed, it was really that! As soon as I updated the OTA url, the problem was gone!
Thanks @jneilliii !
