### ISSUE TITLE
Version 0.4.0 not working with firmware 5.9.1i

### ISSUE THREAD

**Issue by mpfl** [jneilliii/OctoPrint-Tasmota#19]
After a couple of months of happily working, version 0.4.0 no longer works with my firmware 5.9.1i Sonoff Basic.

Sonoff Basic does not have a password set.

Debug log from plugin:

```
[2018-01-12 21:21:29,309] DEBUG: {u'username': u'admin', u'ip': u'192.168.1.52', u'password': u'', u'command': u'checkStatus', u'idx': u''}
[2018-01-12 21:21:29,312] DEBUG: Using authentication for 192.168.1.52.
[2018-01-12 21:21:29,315] DEBUG: Checking status of 192.168.1.52 index .
[2018-01-12 21:21:30,531] DEBUG: 192.168.1.52 index  response: RESULT = {"POWER":"ON"}
POWER = ON (retained)
[2018-01-12 21:21:30,535] ERROR: Invalid ip or unknown error connecting to 192.168.1.52.
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_tasmota/__init__.py", line 134, in check_status
    response = json.loads(webresponse)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[2018-01-12 21:21:30,551] DEBUG: 192.168.1.52 index  is UNKNOWN
[2018-01-12 21:21:30,553] DEBUG: unknown error with 192.168.1.52.
```

Log from Sonoff (I've redacted the MAC address):

```
05:21:24 MQT: tele/sonoffbasic1/STATE = {"Time":"2018-01-13T05:21:24","Uptime":528,"Vcc":3.180,"POWER":"ON","Wifi":{"AP":1,"SSId":"salt","RSSI":84,"APMac":"**:**:**:**:**:**"}}
05:21:30 MQT: stat/sonoffbasic1/RESULT = {"POWER":"ON"}
05:21:30 MQT: stat/sonoffbasic1/POWER = ON (retained)
```

**Comment by jneilliii** [comment]
Ok, I must have had the minimal version wrong with the tasmota firmware.  The response from your plug was using the old format like below.  I can possibly work on this tonight to get it to work with both the older firmware and the newer one, in the meantime you have two options, install the 0.3.0 version of this plugin or upgrade your tasmota firmware.

```
RESULT = {"POWER":"ON"}
POWER = ON (retained)
```
vs the newer firmware response

`{"POWER":"ON"}`

If you're using MQTT you may also prefer my [OctoPrint-TasmotaMQTT](https://github.com/jneilliii/OctoPrint-TasmotaMQTT) plugin.

**Comment by jneilliii** [comment]
Just confirmed, minimum version Tasmota 5.11.0.

**Comment by mpfl** [comment]
Thanks for the quick response. My usual approach is to update firmware as soon as I can, but I'm printing right now :-D
