### ISSUE TITLE
No status with sonoff 4ch 6.6.0 - ERROR: Invalid ip or unknown error connecting to

### ISSUE THREAD

**Issue by beardedfool** [jneilliii/OctoPrint-Tasmota#47]
Hi

Getting this from logs but I can ping this device ok. Any obvious ideas please? Or anything further to test?

Plugin 0.8.6 on Octoprint 1.3.11

```
PING 192.168.21.93 (192.168.21.93) 56(84) bytes of data.
64 bytes from 192.168.21.93: icmp_seq=1 ttl=128 time=4.18 ms
```

```
[2019-10-17 00:29:25,766] ERROR: Invalid ip or unknown error connecting to 192.168.21.93.
Traceback (most recent call last):
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_tasmota/__init__.py", line 158, in check_status
    chk = response["POWER%s" % plugidx]
KeyError: 'POWER'
[2019-10-17 00:33:33,720] ERROR: Invalid ip or unknown error connecting to 192.168.21.93.
Traceback (most recent call last):
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_tasmota/__init__.py", line 158, in check_status
    chk = response["POWER%s" % plugidx]
KeyError: 'POWER'
[2019-10-17 00:33:37,976] ERROR: Invalid ip or unknown error connecting to 192.168.21.93.
Traceback (most recent call last):
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_tasmota/__init__.py", line 158, in check_status
    chk = response["POWER%s" % plugidx]
KeyError: 'POWER'

```

**Comment by jneilliii** [comment]
Thanks for the logs, can you share a screenshot of your plug settings please?

**Comment by achmed20** [comment]
had the same problem but solved it. 2 things you need to do

1. enable "weblog 2" on your tasmotas device. 
2. uncheck the "Single Relay Device" option in the plugin. 

looks like tasmota is using "POWER1" one single device realys now. Im using Sonoff-Tasmota vewrsion 6.4.1 btw
