### ISSUE TITLE
Plugin blocks / slows down loading of octoprint webinterface when tasmota device is unreachable

### ISSUE THREAD

**Issue by hamster65** [jneilliii/OctoPrint-Tasmota#90]
Hi,

When I load octoprint in the browser, it takes a long time (minutes) until all icons show up. During this time, the list of stl files is empty. I can open the octoprint settings, but the settings have not been loaded yet. Octoprint thinks it is not connected to the internet and the plugin list is empty as well.
This happens when octoprint-tasmota is installed and the wifi plug is not reachable (due to bad wifi or simply unplugged).
I guess there is a blocking command some where in the plugin in the connection routine.

It might also slow down transferring files from cura to octoprint, but I am not sure about this.

Best regards.
hamster65

**Comment by jneilliii** [comment]
I'm pretty sure all the requests in the plugin are done using asynchronous techniques, which are non blocking by nature. I wonder if the slow down you are seeing is related to fontawesome loading the icons. What browser?

**Comment by hamster65** [comment]
Firefox and Chromium. Interesting: When I open the octoprint website with Chromium, the tasmota icon and the settings icon is there. The power icon is missing and the notification icon is just a rectangle. At the same time, I cannot connect with another Browser at all, it displays the Octoprint is offline message. Both browsers finish loading at the same time after a 120 second delay.
I refreshed the page on Firefox. All symbols were there, except that power was missing and the one for octoplug looked like a rectangle with 01 in it and a ?.

**Comment by hamster65** [comment]
==> plugin_tasmota_debug.log <==
    return session.request(method=method, url=url, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/raven/breadcrumbs.py", line 341, in send
    resp = real_send(self, request, *args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.10.194', port=80): Max retries exceeded with url: /cm?user=admin&password=&cmnd=Status%200 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x68683cf0>: Failed to establish a new connection: [Errno 110] Connection timed out'))




----------------------------------------------------------------------------------------
delay of about 120 seconds is here, nothing logged during this time
----------------------------------------------------------------------------------------






==> plugin_tasmota_debug.log <==
[2020-10-10 18:04:42,510] ERROR: Invalid ip or unknown error connecting to 192.168.10.194.
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/pi/oprint/lib/python3.7/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/home/pi/oprint/lib/python3.7/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/home/pi/oprint/lib/python3.7/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/home/pi/oprint/lib/python3.7/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/home/pi/oprint/lib/python3.7/site-packages/urllib3/connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x70946650>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/pi/oprint/lib/python3.7/site-packages/urllib3/connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/pi/oprint/lib/python3.7/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.168.10.194', port=80): Max retries exceeded with url: /cm?user=admin&password=&cmnd=Status%200 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70946650>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_tasmota/__init__.py", line 395, in check_status
    webresponse = requests.get("http://" + plugip + "/cm?user=" + plug["username"] + "&password=" + requests.utils.quote(plug["password"]) + "&cmnd=Status%200")
  File "/home/pi/oprint/lib/python3.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/raven/breadcrumbs.py", line 341, in send
    resp = real_send(self, request, *args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.10.194', port=80): Max retries exceeded with url: /cm?user=admin&password=&cmnd=Status%200 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70946650>: Failed to establish a new connection: [Errno 110] Connection timed out'))

==> octoprint.log <==
2020-10-10 18:04:44,439 - octoprint.server.util.sockjs - INFO - User _admin logged in on the socket from client ::ffff:192.168.10.30

==> plugin_tasmota_debug.log <==
[2020-10-10 18:04:47,629] ERROR: Invalid ip or unknown error connecting to 192.168.10.194.
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/pi/oprint/lib/python3.7/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/home/pi/oprint/lib/python3.7/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/home/pi/oprint/lib/python3.7/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/home/pi/oprint/lib/python3.7/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/home/pi/oprint/lib/python3.7/site-packages/urllib3/connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x68756850>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/pi/oprint/lib/python3.7/site-packages/urllib3/connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/pi/oprint/lib/python3.7/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.168.10.194', port=80): Max retries exceeded with url: /cm?user=admin&password=&cmnd=Status%200 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x68756850>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_tasmota/__init__.py", line 395, in check_status
    webresponse = requests.get("http://" + plugip + "/cm?user=" + plug["username"] + "&password=" + requests.utils.quote(plug["password"]) + "&cmnd=Status%200")
  File "/home/pi/oprint/lib/python3.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/raven/breadcrumbs.py", line 341, in send
    resp = real_send(self, request, *args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.10.194', port=80): Max retries exceeded with url: /cm?user=admin&password=&cmnd=Status%200 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x68756850>: Failed to establish a new connection: [Errno 110] Connection timed out'))

**Comment by jneilliii** [comment]
I might know what's going on here now. Need to do some more testing. I bet it would actually effect all my power plugins as they check status of devices on startup/client connection. The actual request.get that is called to get the status of the plugs/relays from the server side might not be getting done in an async thread of it's own.

**Comment by jneilliii** [comment]
I think there might be two ways that I could do to resolve this issue. I could check to verify the ip is active before attempting the request or I could restrict the request retry limit to 1, which would then just delay by a timeout value (my also be configurable). I'll do a little more research on that and see.

**Comment by jneilliii** [comment]
I believe I have this fixed with the above commit. If you'd like to test you can copy/paste the URL below into plugin manager > get more > ...from URL and clicking Install over your existing version.

```
https://github.com/jneilliii/OctoPrint-Tasmota/archive/develop.zip
```

**Comment by hamster65** [comment]
Great, thanks! I unplugged the tasmota plug and octoprint loaded fast. I think it's solved.

**Comment by jneilliii** [comment]
awesome, thanks for confirming.
