### ISSUE TITLE
Thermal runaway code fails to power off

### ISSUE THREAD

**Issue by boingomw** [jneilliii/OctoPrint-Tasmota#94]
Testing the thermal runaway shutoff gave me this message in the debug log:

[2020-10-17 23:52:07,694] ERROR: Invalid ip or unknown error connecting to 192.168.60.23.
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_tasmota/__init__.py", line 370, in turn_off
    chk = response["POWER%s" % plug["idx"]]
UnboundLocalError: local variable 'response' referenced before assignment
[2020-10-17 23:52:07,782] ERROR: Invalid ip or unknown error connecting to 192.168.60.23.
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_tasmota/__init__.py", line 370, in turn_off
    chk = response["POWER%s" % plug["idx"]]
UnboundLocalError: local variable 'response' referenced before assignment

Actually hitting the power icon on octoprint, or having it turn off because of idle timeouts work.

Steps:
1. Setup so it connects and can power on/off the tasmota switch
2. set the bed temp thermal runaway to something low like 33C.
3. Restart Octoprint (just to be safe)
4. Set bed temp to 34 and wait.

Octoprint-Tasmota disconnects at 34C, but does NOT turn off the switch.  Gives the above error.

Hitting the power switch on the octoprint page works, and turns off the switch.

**Comment by boingomw** [comment]
Uh. ok.  Redid all the steps above for a 3rd time, and it works. :| Yay!  Thank you for your support

**Comment by jneilliii** [comment]
Sometimes the settings don't take until an OctoPrint restart. I'm not 100% sure why honestly because I haven't had the time to investigate further but it's a good chance it's related to when I'm initializing the monitoring loop on startup.
